<?php
require_once '../includes/config.php'; requireRole('seller'); $sid=(int)$_SESSION['user']['id']; $message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $name=trim($_POST['name']??'');$category=trim($_POST['category']??'');$brand=trim($_POST['brand']??'');$description=trim($_POST['description']??'');$specifications=trim($_POST['specifications']??'');$warranty=trim($_POST['warranty']??'');$price=(float)($_POST['price']??0);$stock=max(0,(int)($_POST['stock']??0));$image='blank-product.svg';
  if($name===''||$category===''||$price<0)$error='Enter a product name, category, and valid price.';
  $categoryCheck=$conn->prepare('SELECT 1 FROM categories WHERE name=?');$categoryCheck->bind_param('s',$category);$categoryCheck->execute();if(!$error&&!$categoryCheck->get_result()->fetch_assoc())$error='Choose a category managed by an administrator.';
  if(!$error&&isset($_FILES['image'])&&$_FILES['image']['error']!==UPLOAD_ERR_NO_FILE){$upload=$_FILES['image'];$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if($upload['error']!==UPLOAD_ERR_OK)$error='The image upload failed. Please try again.';elseif($upload['size']>5*1024*1024)$error='Product images must be 5 MB or smaller.';else{$mime=(new finfo(FILEINFO_MIME_TYPE))->file($upload['tmp_name']);if(!isset($allowed[$mime]))$error='Upload a JPG, PNG, or WebP image.';else{$fileName=uniqid('product_',true).'.'.$allowed[$mime];$target=__DIR__.'/../assets/images/products/'.$fileName;if(move_uploaded_file($upload['tmp_name'],$target))$image='products/'.$fileName;else $error='Unable to save the product image.';}}}
  if(!$error){$status='Pending';$stmt=$conn->prepare('INSERT INTO products(seller_id,name,category,brand,description,specifications,warranty,price,stock,image,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$stmt->bind_param('issssssdiss',$sid,$name,$category,$brand,$description,$specifications,$warranty,$price,$stock,$image,$status);if($stmt->execute())$message='Product submitted for admin approval.';else $error='Unable to add the product.';}
}
$stmt=$conn->prepare('SELECT * FROM products WHERE seller_id=? ORDER BY created_at DESC');$stmt->bind_param('i',$sid);$stmt->execute();$products=$stmt->get_result();$categories=$conn->query('SELECT name FROM categories ORDER BY name');$pageTitle='My Products';include '../includes/header.php';
?>
<div class="dashboard-grid"><div class="panel"><h2>Add product</h2><?php if($message):?><div class="notice success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<form method="post" enctype="multipart/form-data"><div class="form-group"><label>Product name</label><input name="name" required></div><div class="row"><div class="form-group" style="flex:1"><label>Category</label><select name="category" required><option value="">Choose a category</option><?php while($category=$categories->fetch_assoc()):?><option value="<?=e($category['name'])?>"><?=e($category['name'])?></option><?php endwhile;?></select></div><div class="form-group" style="flex:1"><label>Brand</label><input name="brand"></div></div><div class="form-group"><label>Description</label><textarea name="description"></textarea></div><div class="form-group"><label>Specifications</label><textarea name="specifications"></textarea></div><div class="form-group"><label>Warranty</label><input name="warranty" placeholder="12 months"></div><div class="form-group"><label>Product picture <small class="muted">Optional - JPG, PNG, or WebP, maximum 5 MB</small></label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"></div><div class="row"><div class="form-group" style="flex:1"><label>Price (BDT)</label><input type="number" min="0" step=".01" name="price" required></div><div class="form-group" style="flex:1"><label>Stock</label><input type="number" min="0" name="stock" required></div></div><button class="btn">Submit product</button></form></div>
<div class="panel"><h2>Your catalog</h2><?php while($p=$products->fetch_assoc()):?><div class="row" style="padding:12px 0;border-bottom:1px solid var(--line)"><span><b><?=e($p['name'])?></b><br><small class="muted"><span class="badge <?=e($p['status'])?>"><?=e($p['status'])?></span> <?=$p['stock']?> stock</small></span><b><?=taka($p['price'])?></b></div><?php endwhile;?></div></div>
<?php include '../includes/footer.php'; ?>
