<?php
require_once '../includes/config.php';requireRole('buyer');$uid=(int)$_SESSION['user']['id'];$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  $action=$_POST['action']??'';$orderId=(int)($_POST['order_id']??0);
  if($action==='ticket'){$subject=trim($_POST['subject']??'');$message=trim($_POST['message']??'');if($subject===''||$message==='')$error='Add a subject and message.';else{$stmt=$conn->prepare('INSERT INTO support_tickets(user_id,order_id,subject,message) VALUES(?,?,?,?)');$stmt->bind_param('iiss',$uid,$orderId,$subject,$message);$stmt->execute();$notice='Support ticket created.';}}
  if($action==='return'){$reason=trim($_POST['reason']??'');$check=$conn->prepare("SELECT id FROM orders WHERE id=? AND buyer_id=? AND status='Delivered'");$check->bind_param('ii',$orderId,$uid);$check->execute();if(!$check->get_result()->fetch_assoc())$error='Returns can only be requested for delivered orders.';elseif($reason==='')$error='Tell us why you want to return this order.';else{$stmt=$conn->prepare('INSERT INTO returns(order_id,buyer_id,reason) VALUES(?,?,?)');$stmt->bind_param('iis',$orderId,$uid,$reason);$stmt->execute();$notice='Return request submitted for review.';}}
}
$orders=$conn->prepare('SELECT id,status,created_at FROM orders WHERE buyer_id=? ORDER BY created_at DESC');$orders->bind_param('i',$uid);$orders->execute();$orders=$orders->get_result();$tickets=$conn->prepare('SELECT * FROM support_tickets WHERE user_id=? ORDER BY updated_at DESC');$tickets->bind_param('i',$uid);$tickets->execute();$tickets=$tickets->get_result();$returns=$conn->prepare('SELECT r.*,o.total_amount FROM returns r JOIN orders o ON o.id=r.order_id WHERE r.buyer_id=? ORDER BY r.updated_at DESC');$returns->bind_param('i',$uid);$returns->execute();$returns=$returns->get_result();$pageTitle='Support and returns';include '../includes/header.php'; ?>
<div class="section-head"><div><h1>Support and returns</h1><p class="muted">Create a case for order questions, delivery issues, and delivered-order returns.</p></div></div><?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif;?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?>
<div class="dashboard-grid"><section class="panel"><h2>Contact support</h2><form method="post"><input type="hidden" name="action" value="ticket"><div class="form-group"><label>Related order (optional)</label><select name="order_id"><option value="0">General question</option><?php $orders->data_seek(0);while($o=$orders->fetch_assoc()):?><option value="<?=$o['id']?>">Order #<?=$o['id']?> · <?=e($o['status'])?></option><?php endwhile;?></select></div><div class="form-group"><label>Subject</label><input name="subject" maxlength="150" required></div><div class="form-group"><label>Message</label><textarea name="message" required></textarea></div><button class="btn">Create ticket</button></form></section><section class="panel"><h2>Request a return</h2><form method="post"><input type="hidden" name="action" value="return"><div class="form-group"><label>Delivered order</label><select name="order_id" required><option value="">Choose order</option><?php $orders->data_seek(0);while($o=$orders->fetch_assoc()):if($o['status']==='Delivered'):?><option value="<?=$o['id']?>">Order #<?=$o['id']?></option><?php endif;endwhile;?></select></div><div class="form-group"><label>Reason</label><textarea name="reason" required></textarea></div><button class="btn">Submit return</button></form></section></div>
<section class="panel stack-section"><h2>Your support tickets</h2><div class="table-wrap"><table class="table"><tr><th>Ticket</th><th>Subject</th><th>Status</th><th>Reply</th></tr><?php while($t=$tickets->fetch_assoc()):?><tr><td>#<?=$t['id']?></td><td><?=e($t['subject'])?></td><td><span class="badge"><?=e($t['status'])?></span></td><td><?=e($t['admin_reply']?:'Awaiting support response')?></td></tr><?php endwhile;?></table></div></section><section class="panel stack-section"><h2>Your return requests</h2><div class="table-wrap"><table class="table"><tr><th>Order</th><th>Amount</th><th>Status</th><th>Admin note</th></tr><?php while($r=$returns->fetch_assoc()):?><tr><td>#<?=$r['order_id']?></td><td><?=taka($r['total_amount'])?></td><td><span class="badge"><?=e($r['status'])?></span></td><td><?=e($r['admin_note']?:'Awaiting review')?></td></tr><?php endwhile;?></table></div></section><?php include '../includes/footer.php'; ?>
