<?php
require_once '../includes/config.php';requireRole('admin');$notice='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';$id=(int)($_POST['id']??0);
 if($action==='seller_status'&&in_array($_POST['status']??'', ['Approved','Suspended'],true)){$status=$_POST['status'];$s=$conn->prepare("UPDATE users SET seller_status=? WHERE id=? AND role='seller'");$s->bind_param('si',$status,$id);$s->execute();$notice='Seller status updated.';}
 if($action==='product_status'&&in_array($_POST['status']??'', ['Approved','Rejected','Hidden'],true)){$status=$_POST['status'];$s=$conn->prepare('UPDATE products SET status=? WHERE id=?');$s->bind_param('si',$status,$id);$s->execute();$notice='Listing status updated.';}
 if($action==='ticket'&&in_array($_POST['status']??'', ['Open','In Progress','Resolved','Closed'],true)){$status=$_POST['status'];$reply=trim($_POST['reply']??'');$s=$conn->prepare('UPDATE support_tickets SET status=?,admin_reply=? WHERE id=?');$s->bind_param('ssi',$status,$reply,$id);$s->execute();$notice='Support ticket updated.';}
 if($action==='return'&&in_array($_POST['status']??'', ['Approved','Rejected','Received','Refunded'],true)){$status=$_POST['status'];$note=trim($_POST['note']??'');$s=$conn->prepare('UPDATE returns SET status=?,admin_note=? WHERE id=?');$s->bind_param('ssi',$status,$note,$id);$s->execute();$notice='Return request updated.';}
 if($action==='report'&&in_array($_POST['status']??'', ['Reviewed','Dismissed'],true)){$status=$_POST['status'];$note=trim($_POST['note']??'');$s=$conn->prepare('UPDATE content_reports SET status=?,admin_note=? WHERE id=?');$s->bind_param('ssi',$status,$note,$id);$s->execute();$notice='Content report updated.';}
 if($action==='commission'){$rate=max(0,min(100,(float)($_POST['rate']??5)));$value=(string)$rate;$s=$conn->prepare("UPDATE marketplace_settings SET setting_value=? WHERE setting_key='commission_rate'");$s->bind_param('s',$value);$s->execute();$notice='Marketplace commission updated.';}
 if($action==='admin_add'){$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$employeeId=strtoupper(trim($_POST['employee_id']??''));$password=$_POST['password']??'';if(!preg_match('/^KHB/i',$employeeId))$notice='Admin ID must start with KHB.';elseif($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<6)$notice='Enter a name, valid email, employee ID, and a password of at least 6 characters.';elseif(strlen($employeeId)>50)$notice='Employee IDs can be at most 50 characters.';else{$hash=password_hash($password,PASSWORD_DEFAULT);$role='admin';$s=$conn->prepare('INSERT INTO users(name,email,password,role,employee_id) VALUES(?,?,?,?,?)');$s->bind_param('sssss',$name,$email,$hash,$role,$employeeId);if($s->execute())$notice='New administrator added.';else $notice='That email address or employee ID is already in use.';}}
 if($action==='category_add'){$name=trim($_POST['name']??'');if($name==='')$notice='Enter a category name.';elseif(strlen($name)>80)$notice='Category names can be at most 80 characters.';else{$s=$conn->prepare('INSERT INTO categories(name) VALUES(?)');$s->bind_param('s',$name);if($s->execute())$notice='Category added.';else $notice='That category already exists.';}}
 if($action==='category_rename'){$name=trim($_POST['name']??'');$categoryId=(int)($_POST['category_id']??0);if($name==='')$notice='Enter a category name.';elseif(strlen($name)>80)$notice='Category names can be at most 80 characters.';else{$old=$conn->prepare('SELECT name FROM categories WHERE id=?');$old->bind_param('i',$categoryId);$old->execute();$current=$old->get_result()->fetch_assoc();if(!$current)$notice='Category not found.';else{$conn->begin_transaction();try{$s=$conn->prepare('UPDATE categories SET name=? WHERE id=?');$s->bind_param('si',$name,$categoryId);$s->execute();$s=$conn->prepare('UPDATE products SET category=? WHERE category=?');$s->bind_param('ss',$name,$current['name']);$s->execute();$conn->commit();$notice='Category renamed and linked products updated.';}catch(Exception $e){$conn->rollback();$notice='Unable to rename category. Choose a unique name.';}}}}
 if($action==='category_delete'){$categoryId=(int)($_POST['category_id']??0);$s=$conn->prepare('SELECT name FROM categories WHERE id=?');$s->bind_param('i',$categoryId);$s->execute();$category=$s->get_result()->fetch_assoc();if(!$category)$notice='Category not found.';else{$s=$conn->prepare('SELECT COUNT(*) total FROM products WHERE category=?');$s->bind_param('s',$category['name']);$s->execute();if((int)$s->get_result()->fetch_assoc()['total']>0)$notice='This category is still assigned to products and cannot be deleted.';else{$s=$conn->prepare('DELETE FROM categories WHERE id=?');$s->bind_param('i',$categoryId);$s->execute();$notice='Empty category deleted.';}}}
 if($action==='user_role'&&in_array($_POST['role']??'', ['buyer','seller'],true)){$role=$_POST['role'];$targetId=(int)($_POST['user_id']??0);$currentAdmin=(int)$_SESSION['user']['id'];if($targetId===$currentAdmin)$notice='You cannot change your own role.';else{$target=$conn->prepare('SELECT role FROM users WHERE id=?');$target->bind_param('i',$targetId);$target->execute();$targetUser=$target->get_result()->fetch_assoc();if(!$targetUser)$notice='User not found.';elseif($targetUser['role']==='admin'&&adminCount($conn,'users',"role='admin'")<=1)$notice='At least one administrator must remain.';else{$s=$conn->prepare("UPDATE users SET role=?, seller_status=CASE WHEN ?='seller' THEN 'Pending' ELSE seller_status END WHERE id=?");$s->bind_param('ssi',$role,$role,$targetId);$s->execute();$notice='User role updated.';}}}
}
function adminCount($conn,$table,$condition='1=1'){return (int)$conn->query("SELECT COUNT(*) c FROM `$table` WHERE $condition")->fetch_assoc()['c'];}
$commission=$conn->query("SELECT setting_value FROM marketplace_settings WHERE setting_key='commission_rate'")->fetch_assoc()['setting_value'];
$sales=(float)$conn->query("SELECT COALESCE(SUM(total_amount),0) total FROM orders WHERE status NOT IN ('Cancelled')")->fetch_assoc()['total'];
$sellers=$conn->query("SELECT id,name,email,seller_status,created_at FROM users WHERE role='seller' ORDER BY seller_status='Pending' DESC,created_at DESC");$products=$conn->query("SELECT p.id,p.name,p.category,p.status,u.name seller FROM products p JOIN users u ON u.id=p.seller_id ORDER BY p.status='Pending' DESC,p.created_at DESC");$tickets=$conn->query("SELECT t.*,u.name user_name FROM support_tickets t JOIN users u ON u.id=t.user_id ORDER BY t.status IN ('Open','In Progress') DESC,t.updated_at DESC");$returns=$conn->query("SELECT r.*,u.name buyer_name FROM returns r JOIN users u ON u.id=r.buyer_id ORDER BY r.status='Requested' DESC,r.updated_at DESC");$reports=$conn->query("SELECT cr.*,u.name reporter_name,p.name product_name FROM content_reports cr JOIN users u ON u.id=cr.reporter_id LEFT JOIN products p ON p.id=cr.product_id ORDER BY cr.status='Open' DESC,cr.created_at DESC");$categories=$conn->query("SELECT c.id,c.name,COUNT(p.id) product_count FROM categories c LEFT JOIN products p ON p.category=c.name GROUP BY c.id,c.name ORDER BY c.name");$users=$conn->query("SELECT id,name,email,role,seller_status,employee_id,created_at FROM users ORDER BY created_at DESC");
$pageTitle='Admin dashboard';include '../includes/header.php'; ?>
<div class="section-head"><div><h1>Admin dashboard</h1><p class="muted">Marketplace moderation, customer operations, and platform controls.</p></div></div><?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif;?>
<div class="stats"><div class="stat">Users<b><?=adminCount($conn,'users')?></b></div><div class="stat">Pending sellers<b><?=adminCount($conn,'users',"role='seller' AND seller_status='Pending'")?></b></div><div class="stat">Pending listings<b><?=adminCount($conn,'products',"status='Pending'")?></b></div><div class="stat">Platform sales<b><?=taka($sales)?></b></div></div>
<div class="dashboard-grid"><section class="panel"><h2>Marketplace fee</h2><p class="muted">Commission is calculated for reporting and does not change checkout totals.</p><form method="post" class="inline-form"><input type="hidden" name="action" value="commission"><label>Commission % <input type="number" name="rate" min="0" max="100" step=".1" value="<?=e($commission)?>"></label><button class="btn small">Save</button></form><p><b>Estimated commission:</b> <?=taka($sales*(float)$commission/100)?></p></section><section class="panel"><h2>Moderation queue</h2><p class="muted"><?=adminCount($conn,'support_tickets',"status IN ('Open','In Progress')")?> open support cases · <?=adminCount($conn,'returns',"status='Requested'")?> return requests · <?=adminCount($conn,'content_reports',"status='Open'")?> content reports</p></section></div>
<section class="panel stack-section"><h2>Category management</h2><p class="muted">Rename updates all linked products. A category can only be deleted when no products use it.</p><form method="post" class="inline-form"><input type="hidden" name="action" value="category_add"><input name="name" maxlength="80" required placeholder="New category name"><button class="btn small">Add category</button></form><div class="table-wrap" style="margin-top:14px"><table class="table"><tr><th>Category</th><th>Products</th><th>Actions</th></tr><?php while($category=$categories->fetch_assoc()):?><tr><td><?=e($category['name'])?></td><td><?=$category['product_count']?></td><td><form method="post" class="inline-form"><input type="hidden" name="category_id" value="<?=$category['id']?>"><input name="name" maxlength="80" required value="<?=e($category['name'])?>"><button class="btn small" name="action" value="category_rename">Rename</button><button class="btn small danger" name="action" value="category_delete" data-confirm="Delete this empty category?">Delete</button></form></td></tr><?php endwhile;?></table></div></section>
<section class="panel stack-section"><h2>Add new administrator</h2><p class="muted">Every administrator must have a unique employee ID.</p><form method="post" class="inline-form"><input type="hidden" name="action" value="admin_add"><input name="name" maxlength="100" required placeholder="Full name"><input type="email" name="email" required placeholder="Email"><input name="employee_id" maxlength="50" required placeholder="Employee ID"><input type="password" name="password" minlength="6" required placeholder="Temporary password"><button class="btn small">Add administrator</button></form></section>
<section class="panel stack-section"><h2>User-role management</h2><p class="muted">Role changes take effect immediately. New sellers require approval before they can manage listings. Use the form above to add administrators.</p><div class="table-wrap"><table class="table"><tr><th>User</th><th>Email</th><th>Employee ID</th><th>Role</th><th>Seller status</th><th>Action</th></tr><?php while($user=$users->fetch_assoc()):?><tr><td><?=e($user['name'])?></td><td><?=e($user['email'])?></td><td><?= $user['role']==='admin' ? e($user['employee_id']) : '—' ?></td><td><span class="badge"><?=e($user['role'])?></span></td><td><?php if($user['role']==='seller'):?><span class="badge"><?=e($user['seller_status'])?></span><?php else:?>—<?php endif;?></td><td><?php if((int)$user['id']===(int)$_SESSION['user']['id']):?><span class="muted">Current administrator</span><?php else:?><form method="post" class="inline-form"><input type="hidden" name="action" value="user_role"><input type="hidden" name="user_id" value="<?=$user['id']?>"><select name="role"><option value="buyer" <?=$user['role']==='buyer'?'selected':''?>>Buyer</option><option value="seller" <?=$user['role']==='seller'?'selected':''?>>Seller</option></select><button class="btn small">Update role</button></form><?php endif;?></td></tr><?php endwhile;?></table></div></section>
<section class="panel stack-section"><h2>Seller approvals</h2><div class="table-wrap"><table class="table"><tr><th>Seller</th><th>Email</th><th>Status</th><th>Action</th></tr><?php while($s=$sellers->fetch_assoc()):?><tr><td><?=e($s['name'])?></td><td><?=e($s['email'])?></td><td><span class="badge"><?=e($s['seller_status'])?></span></td><td><form method="post" class="inline-form"><input type="hidden" name="action" value="seller_status"><input type="hidden" name="id" value="<?=$s['id']?>"><select name="status"><option>Approved</option><option>Suspended</option></select><button class="btn small">Update</button></form></td></tr><?php endwhile;?></table></div></section>
<section class="panel stack-section"><h2>Product approvals</h2><div class="table-wrap"><table class="table"><tr><th>Product</th><th>Seller</th><th>Category</th><th>Status</th><th>Action</th></tr><?php while($p=$products->fetch_assoc()):?><tr><td><?=e($p['name'])?></td><td><?=e($p['seller'])?></td><td><?=e($p['category'])?></td><td><span class="badge"><?=e($p['status'])?></span></td><td><form method="post" class="inline-form"><input type="hidden" name="action" value="product_status"><input type="hidden" name="id" value="<?=$p['id']?>"><select name="status"><option>Approved</option><option>Rejected</option><option>Hidden</option></select><button class="btn small">Update</button></form></td></tr><?php endwhile;?></table></div></section>
<section class="panel stack-section"><h2>Support tickets</h2><?php while($t=$tickets->fetch_assoc()):?><form method="post" class="case-row"><input type="hidden" name="action" value="ticket"><input type="hidden" name="id" value="<?=$t['id']?>"><div><b>#<?=$t['id']?> <?=e($t['subject'])?></b><p class="muted"><?=e($t['user_name'])?>: <?=e($t['message'])?></p></div><select name="status"><option><?=$t['status']?></option><option>In Progress</option><option>Resolved</option><option>Closed</option></select><input name="reply" value="<?=e($t['admin_reply'])?>" placeholder="Reply"><button class="btn small">Save</button></form><?php endwhile;?></section>
<section class="panel stack-section"><h2>Return requests</h2><?php while($r=$returns->fetch_assoc()):?><form method="post" class="case-row"><input type="hidden" name="action" value="return"><input type="hidden" name="id" value="<?=$r['id']?>"><div><b>Return #<?=$r['id']?> for order #<?=$r['order_id']?></b><p class="muted"><?=e($r['buyer_name'])?>: <?=e($r['reason'])?></p></div><select name="status"><option><?=$r['status']?></option><option>Approved</option><option>Rejected</option><option>Received</option><option>Refunded</option></select><input name="note" value="<?=e($r['admin_note'])?>" placeholder="Admin note"><button class="btn small">Save</button></form><?php endwhile;?></section>
<section class="panel stack-section"><h2>Reported content</h2><?php while($r=$reports->fetch_assoc()):?><form method="post" class="case-row"><input type="hidden" name="action" value="report"><input type="hidden" name="id" value="<?=$r['id']?>"><div><b>Report #<?=$r['id']?> <?=e($r['product_name']?:'Review or other content')?></b><p class="muted"><?=e($r['reporter_name'])?>: <?=e($r['reason'])?></p></div><select name="status"><option><?=$r['status']?></option><option>Reviewed</option><option>Dismissed</option></select><input name="note" value="<?=e($r['admin_note'])?>" placeholder="Admin note"><button class="btn small">Save</button></form><?php endwhile;?></section>
<?php include '../includes/footer.php'; ?>
